ecomsite/cart/urls.py
# cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.view_cart, name='view_cart'),
    path('add/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove/<int:cart_item_id>/', views.remove_from_cart, name='remove_from_cart'),
]

ecomsite/ecomsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("store/", include("product.urls")),
    path('users/', include("users.urls")),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
] +  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecomsite/order/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
    path('', views.order_now, name='order_now'),
]

ecomsite/product/urls.py
from django.urls import path
from .views import ProductListView, ProductDetailView
app_name = "product"
urlpatterns = [
    path("", ProductListView.as_view(), name="products"),
    path('product/<int:pk>/', ProductDetailView.as_view(), name='product_detail'),
]

ecomsite/users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
app_name = 'users'
urlpatterns = [
    path('register/', views.register_user, name="register"),
    path('login/', auth_views.LoginView.as_view(template_name="users/login.html"), name="login"),
    path('logout/', auth_views.LogoutView.as_view(template_name="users/logout.html"), name="logout"),
    path('logout-form/', views.logout_form, name="logout-form"),
]

ecomsite/cart/models.py
from django.db import models
from django.contrib.auth import get_user_model
from product.models import Product

User = get_user_model()

class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username}'s cart"

class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return f"{self.cart.user.username}'s cartitem"

ecomsite/order/models.py
from django.db import models
from cart.models import Cart


# Define your Order model
class Order(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)


    def __str__(self) -> str:
        user_name = self.cart.user.username
        return f"Order for {user_name}"

ecomsite/product/models.py
from django.db import models

# Create your models here.
class Product(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    category = models.CharField(max_length=50)
    image = models.ImageField(upload_to='product_images/', default='product_images/placeholder_product.webp')
    stock_quantity = models.IntegerField(default=0)
    date_added = models.DateTimeField(auto_now_add=True)
    brand = models.CharField(max_length=50)
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.name

ecomsite/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class CustomUser(AbstractUser):
    shipping_address = models.TextField(blank=True)
    phone_number = models.CharField(max_length=15, blank=True)


    def __str__(self):
        return self.username

ecomsite/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from .models import CustomUser

class RegistrationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = ['username', 'email', 'shipping_address', 'phone_number']

ecomsite/cart/views.py
from django.shortcuts import render, redirect
from .models import Cart, CartItem
from product.models import Product
from django.contrib import messages
from django.contrib.auth.decorators import login_required

@login_required
def view_cart(request):
    cart = Cart.objects.get_or_create(user=request.user)[0]
    cart_items = cart.cartitem_set.all()
    return render(request, 'cart/cart.html', {'cart': cart, 'cart_items': cart_items})
@login_required
def add_to_cart(request, product_id):
    cart, created = Cart.objects.get_or_create(user=request.user)
    product = Product.objects.get(id=product_id)
    
    # Check if the product is already in the cart
    cart_item, cart_item_created = CartItem.objects.get_or_create(cart=cart, product=product)
    
    # If the cart item is newly created, set its quantity to 1
    if cart_item_created:
        cart_item.quantity = 1
        cart_item.save()
        messages.success(request, f'{product.name} added to your cart.')
    else:
        # If the cart item already exists, increment its quantity by 1
        cart_item.quantity += 1
        cart_item.save()
        messages.success(request, f'{product.name} quantity updated in your cart.')

    return redirect('cart:view_cart')
@login_required
def remove_from_cart(request, cart_item_id):
    CartItem.objects.get(id=cart_item_id).delete()
    return redirect('cart:view_cart')

ecomsite/order/views.py
from django.shortcuts import redirect, render
from .models import  Order
from django.contrib.auth import get_user_model
from cart.models import CartItem


User = get_user_model()

def order_now(request):
    if request.method == 'POST':
        # Assuming the user is authenticated and their cart is stored in the session
        user_id = request.session['_auth_user_id']
        print(f"user id: {user_id}")
        user = User.objects.get(pk=user_id)
        print(f"user : {user}")
        user_cart = user.cart_set.all()[0]
        print(f"user cart: {user_cart}")
        order = Order.objects.create(cart=user_cart)
        # CartItem.objects.filter(cart=user_cart).delete() # create order item caz products in oder are cartitem and if we remove cartitem products in order will also get removed 
    return render(request, 'order/order.html', {"cart": user_cart})

ecomsite/product/views.py
from django.db.models.query import QuerySet
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import Product


class ProductListView(ListView):
    model = Product
    template_name = 'product/index.html'
    context_object_name = 'products'
    paginate_by = 3  # Number of products per page
        
    def post(self, request, *args, **kwargs):
        # Handle POST request for search form submission
        query = self.request.POST.get('search')
        if query:
            products = Product.objects.filter(name__icontains=query)
        else:
            products = Product.objects.all()
        return render(request, self.template_name, {'products': products})

class ProductDetailView(DetailView):
    model = Product
    template_name = 'product/detail.html' 
    context_object_name = 'product' 

ecomsite/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from .forms import RegistrationForm
from django.contrib.auth.decorators import login_required

# Create your views here.
def register_user(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            print(request.POST)  # Debug statement to print form data
            username = form.cleaned_data.get('username')
            messages.success(request, f"Welcome {username} u have successfully registered!")
            return redirect("users:login")
    else:
        form = RegistrationForm()
    
    return render(request, "users/register.html", {'form': form,})

@login_required
def logout_form(request):
    return render(request, "users/logout_form.html")

ecomsite/cart/templates/cart/cart.html
{% extends 'product/base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'cart/cart.css' %}">
{% endblock %}
{% block form_class %}hide-search-bar{% endblock %}
{% block content %}
<div class="cart-container">
<form action="{% url 'order:order_now' %}" method="post">
    {% csrf_token %}
 <h1 class="cart-heading">Your Shopping Cart</h1>
    {% if cart_items %}
        <ul class="cart-ul" >
            {% for cart_item in cart_items %}
                <li>
                    {{ cart_item.product.name }} - Quantity: {{ cart_item.quantity }}
                    <a href="{% url 'cart:remove_from_cart' cart_item.id %}">Remove</a>
                </li>
            {% endfor %}
        </ul>
        <p class="cart-summary" >Total Items: {{ cart_items|length }}</p>
        <button type="submit" class="cart-btn">order now</button>
    {% else %}
        <p class="empty-cart" >Your cart is empty.</p>
    {% endif %}
    </form>
    <a class="cart-btn" href="{% url 'product:products' %}">Continue Shopping</a>
    </div>
{% endblock %}

ecomsite/order/templates/order/order.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Order Confirmation</title>
</head>
<body>
    <h1>Order Confirmation</h1>
    <p>Hey there!</p>
    <p>Your order has been successfully placed for the following items:</p>
    <ul>
        {% for item in cart.cartitem_set.all %}
            <li>{{ item.product.name }} - Quantity: {{ item.quantity }} - Price: ${{ item.product.price }}</li>
        {% endfor %}
    </ul>
    <p>Thank you for your order!</p>
    <a href="{% url 'product:products' %}">back to home page?</a>
</body>
</html>

ecomsite/product/templates/product/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ShopApp</title>
    <link rel="stylesheet" href="{% static 'product/base.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />
    {% block css %}
    {% endblock %}
</head>
<body>
    
    <!-- for medium and large screens -->
    <nav class="navbar">
        <div class="container">
            <a href="{% url 'product:products' %}" class="brand">Shop App</a>
            
            <ul class="menu">
                <li><a href="{% url 'users:register' %}">Register</a></li>
                <li><a href="{% url 'cart:view_cart' %}">Cart</a></li>
                
                <li> {% if user.is_authenticated %}
                <a href="{% url 'users:logout-form' %}">Logout</a>
                {% else %}
                <a href="{% url 'users:login' %}">Login</a>
                {% endif %}</li>
                <li><a href="#">About</a></li>
            </ul>
        </div>
        <form class="search-bar {% block form_class %}{% endblock %}" method="post">
            {%csrf_token%}
            <input type="text" name="search" placeholder="Search Products Here">
            <button type="submit">search</button>
        </form>
        
    </nav>

    <!-- for small screens -->
    <nav class="navbar-mob" >
        <div class="nav-mob-head">
            <a href="{% url 'product:products' %}" class="nav-mob-brand">Shop App</a>
            <div class="nav-mob-menu"><span class="material-symbols-outlined">menu</span></div>
            
        </div>
        <form class="nav-mob-search">
            <input type="text" placeholder="Search Products Here">
            <button type="submit">search</button>
        </form>
    </nav>

    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{message.tags}}">
      {{ message }}
      <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
    </div>
    {% endfor %}
    {% endif %}


    {% block content %}
    {% endblock %}
</body>
</html>

ecomsite/product/templates/product/detail.html
{% extends 'product/base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'product/details.css' %}">
{% endblock %}
{% block form_class %}hide-search-bar{% endblock %}
{% block content %}
<div class="product-detail-card">
    <div class="product-image">
        <img src="{{ product.image.url }}" alt="{{ product.name }}" width="200">
    </div>
    <div class="product-details">
        <h1>{{ product.name }}</h1>
        <p><strong>Description:</strong> {{ product.description }}</p>
        <p><strong>Price:</strong> ${{ product.price }}</p>
        <p><strong>Category:</strong> {{ product.category }}</p>
        <p><strong>Brand:</strong> {{ product.brand }}</p>
        <p><strong>Stock Quantity:</strong> {{ product.stock_quantity }}</p>
        <a  href="{% url 'cart:add_to_cart' product.id %}" class="add-to-cart-detail">Add to Cart</a>
    </div>
    
    
</div>
{% endblock %}

ecomsite/product/templates/product/index.html
{% extends 'product/base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'product/index.css' %}">
{% endblock %}
{% block content %}
<h1 class="home-heading">Discover, Explore, Shop!</h1>
<div class="home-grid">
{% for product in products %}
<div class="home-card">
    <div class="home-card-img">
    <img  src="{{ product.image.url }}" alt="{{product.name}}">
    </div>
    <div class="home-card-details">
        <h4>{{product.name}}</h4>
        <p>${{product.price}}</p>
        <div class="home-card-btns">
            <a href="{% url 'cart:add_to_cart' product.id %}">add to cart</a> 
            
            <a href="{% url 'product:product_detail' product.id  %}">View Product</a>
            
        </div>
    </div>
</div>
{% endfor %}
</div>
<!-- Pagination links -->
<div class="pagination">
    <span class="step-links">
        {% if is_paginated %}
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        {% endif %}
    </span>
</div>
{% endblock %}

ecomsite/users/templates/users/login.html
{% extends 'product/base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'users/register.css' %}">
{% endblock %}
{% block form_class %}hide-search-bar{% endblock %}
{% block content %}
<div class="register-container">
    <div class="register-header">Login</div>
    <div class="register-body">
        <form method="post">
            {%csrf_token%}
            {{form}}
            <button type="submit" >Login</button>
        </form>
    </div>
</div>

{% endblock %}

ecomsite/users/templates/users/logout.html
<h2>You have been logged out</h2>
<a href="{% url 'users:login' %}">Login</a>

ecomsite/users/templates/users/logout_form.html
{% extends 'product/base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'users/register.css' %}">
{% endblock %}
{% block form_class %}hide-search-bar{% endblock %}
{% block content %}

<div class="register-container">
    <div class="register-header">Logout</div>
    <div class="register-body">
        <form action="{% url 'users:logout' %}" method="post">
        {% csrf_token %}
        <button type="submit">Logout</button>
</form>
    </div>
</div>
{% endblock %}

ecomsite/users/templates/users/register.html
{% extends 'product/base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'users/register.css' %}">
{% endblock %}
{% block form_class %}hide-search-bar{% endblock %}
{% block content %}
<div class="container">
    <div class="register-header">Register</div>
    <div class="register-body">
        <form method="post">
            {%csrf_token%}
            {{form}}
            <button type="submit" >SignUp</button>
        </form>
    </div>
</div>

{% endblock %}